---
title: "Playing with mismatch data."
author: "atb abelew@gmail.com"
date: "`r Sys.Date()`"
output:
  html_document:
    code_download: true
    code_folding: show
    fig_caption: true
    fig_height: 7
    fig_width: 7
    highlight: tango
    keep_md: false
    mode: selfcontained
    number_sections: true
    self_contained: true
    theme: readable
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  rmdformats::readthedown:
    code_download: true
    code_folding: show
    df_print: paged
    fig_caption: true
    fig_height: 7
    fig_width: 7
    highlight: tango
    width: 300
    keep_md: false
    mode: selfcontained
    toc_float: true
  BiocStyle::html_document:
    code_download: true
    code_folding: show
    fig_caption: true
    fig_height: 7
    fig_width: 7
    highlight: tango
    keep_md: false
    mode: selfcontained
    toc_float: true
---

<style type="text/css">
body, td {
  font-size: 16px;
}
code.r{
  font-size: 16px;
}
pre {
 font-size: 16px
}
</style>

```{r options, include=FALSE}
library("hpgltools")
tt <- devtools::load_all("/data/hpgltools")
knitr::opts_knit$set(width=120,
                     progress=TRUE,
                     verbose=TRUE,
                     echo=TRUE)
knitr::opts_chunk$set(error=TRUE,
                      dpi=96)
old_options <- options(digits=4,
                       stringsAsFactors=FALSE,
                       knitr.duplicate.label="allow")
ggplot2::theme_set(ggplot2::theme_bw(base_size=10))
rundate <- format(Sys.Date(), format="%Y%m%d")
previous_file <- "index.Rmd"
ver <- "20191201"

##tmp <- sm(loadme(filename=paste0(gsub(pattern="\\.Rmd", replace="", x=previous_file), "-v", ver, ".rda.xz")))
##rmd_file <- "03_expression_infection_20180822.Rmd"
```

# Messing around with a table of mismatches

```{r testing}
library(tidyr)
library(dplyr)
library(janitor)


parsed_to_shared <- function(file, min_reads=3) {
  tbl <- readr::read_tsv(file, col_names=FALSE)
  colnames(tbl) <- c("index", "read", "total_reads", "position", "type", "ref", "hit")

  ## Extract the set of entries with >= 3 reads.
  three_plus_idx <- tbl[["total_reads"]] >= min_reads
  three_plus <- tbl[three_plus_idx, ]

  ## Count how many entries exist for each index/position/etc.
  ## Looking for duplicates of index, position, type, ref, and hit should tell us
  ## that if there are 4 total reads for a given index,type,etc and we see 4 copies
  ## of that entry, then all 4 agree and are therefore interesting to us.
  shared <- three_plus %>%
    get_dupes(index, position, type, ref, hit)
  all_shared_idx <- shared[["dupe_count"]] == shared[["total_reads"]]
  all_shared <- shared[all_shared_idx, ]

  ## Now we should have a bunch of copies of the same entry, so lets winnow that down.
  shared_individual_idx <- all_shared[, c("index", "position", "type", "ref", "hit")] %>%
    duplicated()
  shared_individuals <- all_shared[! shared_individual_idx,
                                   c("index", "position", "type", "ref", "hit", "total_reads")]
  shared_individuals[["string"]] <- paste0(shared_individuals[["position"]], "_",
                                           shared_individuals[["type"]], "_",
                                           shared_individuals[["ref"]], "_",
                                           shared_individuals[["hit"]])

  ## Now let us ask how many indexes share a single position/type/etc.
  shared_all <- shared_individuals[, c("string", "total_reads")] %>%
    get_dupes(string) %>%
    group_by(string) %>%
    summarise_all(sum)

  return(shared_all)
}

s1_shared <- parsed_to_shared("s1/merged_fasta_parsed.txt.xz")
s2_shared <- parsed_to_shared("s2/merged_fasta_parsed.txt.xz")
s3_shared <- parsed_to_shared("s3/merged_fasta_parsed.txt.xz")

sall <- merge(s1_shared, s2_shared, by.x="string", by.y="string", all.x=TRUE, all.y=TRUE)
colnames(sall) <- c("string", "s1_count", "s1_total", "s2_count", "s2_total")
sall <- merge(sall, s3_shared, by.x="string", by.y="string", all.x=TRUE, all.y=TRUE)
colnames(sall) <- c("string", "s1_count", "s1_total", "s2_count", "s2_total", "s3_count", "s3_total")

sall_df <- as.data.frame(sall)
sall_df <- sall_df[, c("s1_count", "s2_count", "s3_count")]
rownames(sall_df) <- gsub(pattern="^([[:digit:]][[:digit:]])_",
                          replacement="0\\1_",
                          x=sall[["string"]])
resorted <- order(rownames(sall_df))
sall_df <- sall_df[resorted, ]
written <- write_xlsx(data=sall_df, excel="first_pass.xlsx")
```


```{r saveme, eval=FALSE}
pander::pander(sessionInfo())
message(paste0("This is hpgltools commit: ", get_git_commit()))
this_save <- paste0(gsub(pattern="\\.Rmd", replace="", x=rmd_file), "-v", ver, ".rda.xz")
message(paste0("Saving to ", this_save))
tmp <- sm(saveme(filename=this_save))
```
